spring.application.name=platform
spring.mongodb.uri=mongodb://localhost:27017/social-media

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=YOUR_SENDING_EMAIL_ID
spring.mail.password=SENDING_EMAIL_ID_APP_PASSWORD

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

